version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    networks:
      - ytprj-network
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DEBUG: ${DEBUG}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

    networks:
      - ytprj-network
    volumes:
      - .:/app

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - ytprj-network
    environment:
      JENKINS_OPTS: --httpPort=8080

networks:
  ytprj-network:

volumes:
  db_data:
  jenkins_home: