version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    networks:
      - ytprj-network
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DEBUG: ${DEBUG}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

    networks:
      - ytprj-network
    volumes:
      - .:/app

networks:
  ytprj-network:

volumes:
  db_data: